export type TemperamentId =
  | "12tet"
  | "19tet"
  | "31tet"
  | "43tet"
  | "45tet"
  | "53tet"
  | "55tet"
  | "quarter"
  | "meantone"
  | "pythagorean"
  | "indian"
  | "arab"
  | "persian";

export interface TemperamentOption {
  id: TemperamentId;
  label: string;
}

export const TEMPERAMENT_OPTIONS: TemperamentOption[] = [
  { id: "12tet", label: "12-TET" },
  { id: "19tet", label: "19-TET" },
  { id: "quarter", label: "24-TET" },
  { id: "31tet", label: "31-TET" },
  { id: "43tet", label: "43-TET" },
  { id: "45tet", label: "45-TET" },
  { id: "53tet", label: "53-TET" },
  { id: "55tet", label: "55-TET" },
  { id: "meantone", label: "Meantone 1/4 comma" },
  { id: "pythagorean", label: "Pythagorean" },
  { id: "indian", label: "Indian" },
  { id: "arab", label: "Arab-Pythagorean" },
  { id: "persian", label: "Persian" },
];

export interface OctaveNoteDef {
  key: string;
  label: string;
  alias: string;
  cents: number;
}

export const TEMPERAMENT_NOTE_MAP: Record<TemperamentId, OctaveNoteDef[]> = {
  "12tet": [
    { key: "c",  label: "C",  alias: "B♯",	cents: 0 },
    { key: "cs", label: "C♯", alias: "D♭",	cents: 100 },
    { key: "d",  label: "D",  alias: "",		cents: 200 },
    { key: "ds", label: "D♯", alias: "E♭",	cents: 300 },
    { key: "e",  label: "E",  alias: "F♭",	cents: 400 },
    { key: "f",  label: "F",  alias: "E♯",	cents: 500 },
    { key: "fs", label: "F♯", alias: "G♭",  cents: 600 },
    { key: "g",  label: "G",  alias: "",    cents: 700 },
    { key: "gs", label: "G♯", alias: "A♭",	cents: 800 },
    { key: "a",  label: "A",  alias: "",		cents: 900 },
    { key: "as", label: "A♯", alias: "B♭",	cents: 1000 },
    { key: "b",  label: "B",  alias: "C♭",	cents: 1100 },
  ],

  "19tet": [
    { key: "c",  label: "C",  alias: "",   cents: 0 },
    { key: "cs", label: "C♯", alias: "",   cents: 63.16 },
    { key: "db", label: "D♭", alias: "",   cents: 126.32 },
    { key: "d",  label: "D",  alias: "",   cents: 189.47 },
    { key: "ds", label: "D♯", alias: "",   cents: 252.63 },
    { key: "eb", label: "E♭", alias: "",   cents: 315.79 },
    { key: "e",  label: "E",  alias: "",   cents: 378.95 },
    { key: "es", label: "E♯", alias: "F♭", cents: 442.11 },
    { key: "f",  label: "F",  alias: "",   cents: 505.26 },
    { key: "fs", label: "F♯", alias: "",   cents: 568.42 },
    { key: "gb", label: "G♭", alias: "",   cents: 631.58 },
    { key: "g",  label: "G",  alias: "",   cents: 694.74 },
    { key: "gs", label: "G♯", alias: "",   cents: 757.89 },
    { key: "ab", label: "A♭", alias: "",   cents: 821.05 },
    { key: "a",  label: "A",  alias: "",   cents: 884.21 },
    { key: "as", label: "A♯", alias: "",   cents: 947.37 },
    { key: "bb", label: "B♭", alias: "",   cents: 1010.53 },
    { key: "b",  label: "B",  alias: "",   cents: 1073.68 },
    { key: "bs", label: "B♯", alias: "C♭", cents: 1136.84 },
  ],

  "31tet": [
    { key: "c",  label: "C",	alias: "",    cents: 0 },
    { key: "c+", label: "C+",	alias: "D♭♭", cents: 38.71 },
    { key: "cs", label: "C♯", alias: "",    cents: 77.42 },
    { key: "db", label: "D♭", alias: "",    cents: 116.13 },
    { key: "d-", label: "D-",	alias: "C♯♯", cents: 154.84 },
    { key: "d",  label: "D",  alias: "", 		cents: 193.55 },
    { key: "d+", label: "D+",	alias: "E♭♭", cents: 232.26 },
    { key: "ds", label: "D♯", alias: "",    cents: 270.97 },
    { key: "eb", label: "E♭", alias: "",    cents: 309.68 },
    { key: "e-", label: "E-",	alias: "D♯♯", cents: 348.39 },
    { key: "e",  label: "E",	alias: "",    cents: 387.10 },
    { key: "e+", label: "E+", alias: "F♭",  cents: 425.81 },
    { key: "f-", label: "F-", alias: "E♯",  cents: 464.52},
    { key: "f",  label: "F",  alias: "",    cents: 503.23 },
    { key: "f+", label: "F+",	alias: "G♭♭", cents: 541.94 },
    { key: "fs", label: "F♯", alias: "",    cents: 580.65 },
    { key: "gb", label: "G♭",	alias: "",    cents: 619.35 },
    { key: "g-", label: "G-",	alias: "F♯♯",	cents: 658.06 },
    { key: "g",  label: "G",  alias: "", 		cents: 696.77 },
    { key: "g+", label: "G+",	alias: "A♭♭", cents: 735.48 },
    { key: "gs", label: "G♯",	alias: "",    cents: 774.19 },
    { key: "ab", label: "A♭", alias: "",    cents: 812.90 },
    { key: "a-", label: "A-",	alias: "G♯♯", cents: 851.61 },
    { key: "a",  label: "A",  alias: "", 		cents: 890.32 },
    { key: "a+", label: "A+",	alias: "B♭♭", cents: 929.03 },
    { key: "as", label: "A♯", alias: "",    cents: 967.74 },
    { key: "bb", label: "B♭", alias: "",    cents: 1006.45 },
    { key: "b-", label: "B-",	alias: "A♯♯", cents: 1045.16 },
    { key: "b",  label: "B",  alias: "",    cents: 1083.87 },
    { key: "b+", label: "B+", alias: "C♭", 	cents: 1122.58 },
    { key: "c-", label: "C-", alias: "B♯", 	cents: 1161.29 },
  ],

  "43tet": [
    { key: "c", label: "C", alias: "", cents: 0 },
    { key: "dbb", label: "D♭♭", alias: "", cents: 27.91 },
    { key: "bss", label: "B♯♯", alias: "", cents: 55.81 },
    { key: "cs", label: "C♯", alias: "", cents: 83.72 },
    { key: "db", label: "D♭", alias: "", cents: 111.63 },
    { key: "ebbb", label: "E♭♭♭", alias: "", cents: 139.53 },
    { key: "css", label: "C♯♯", alias: "", cents: 167.44 },
    { key: "d", label: "D", alias: "", cents: 195.35 },
    { key: "ebb", label: "E♭♭", alias: "", cents: 223.26 },
    { key: "csss", label: "C♯♯♯", alias: "", cents: 251.16 },
    { key: "ds", label: "D♯", alias: "", cents: 279.07 },
    { key: "eb", label: "E♭", alias: "", cents: 306.98 },
    { key: "fbb", label: "F♭♭", alias: "", cents: 334.88 },
    { key: "dss", label: "D♯♯", alias: "", cents: 362.79 },
    { key: "e", label: "E", alias: "", cents: 390.7 },
    { key: "fb", label: "F♭", alias: "", cents: 418.6 },
    { key: "gbbb", label: "G♭♭♭", alias: "", cents: 446.51 },
    { key: "es", label: "E♯", alias: "", cents: 474.42 },
    { key: "f", label: "F", alias: "", cents: 502.33 },
    { key: "gbb", label: "G♭♭", alias: "", cents: 530.23 },
    { key: "ess", label: "E♯♯", alias: "", cents: 558.14 },
    { key: "fs", label: "F♯", alias: "", cents: 586.05 },
    { key: "gb", label: "G♭", alias: "", cents: 613.95 },
    { key: "abbb", label: "A♭♭♭", alias: "", cents: 641.86 },
    { key: "fss", label: "F♯♯", alias: "", cents: 669.77 },
    { key: "g", label: "G", alias: "", cents: 697.67 },
    { key: "abb", label: "A♭♭", alias: "", cents: 725.58 },
    { key: "fsss", label: "F♯♯♯", alias: "", cents: 753.49 },
    { key: "gs", label: "G♯", alias: "", cents: 781.4 },
    { key: "ab", label: "A♭", alias: "", cents: 809.3 },
    { key: "bbbb", label: "B♭♭♭", alias: "", cents: 837.21 },
    { key: "gss", label: "G♯♯", alias: "", cents: 865.12 },
    { key: "a", label: "A", alias: "", cents: 893.02 },
    { key: "bbb", label: "B♭♭", alias: "", cents: 920.93 },
    { key: "cbbb", label: "C♭♭♭", alias: "", cents: 948.84 },
    { key: "as", label: "A♯", alias: "", cents: 976.74 },
    { key: "bb", label: "B♭", alias: "", cents: 1004.65 },
    { key: "cbb", label: "C♭♭", alias: "", cents: 1032.56 },
    { key: "ass", label: "A♯♯", alias: "", cents: 1060.47 },
    { key: "b", label: "B", alias: "", cents: 1088.37 },
    { key: "cb", label: "C♭", alias: "", cents: 1116.28 },
    { key: "dbbb", label: "D♭♭♭", alias: "", cents: 1144.19 },
    { key: "bs", label: "B♯", alias: "", cents: 1172.09 },
  ],

  "45tet": [
    { key: "c", label: "C", alias: "", cents: 0 },
    { key: "dbbb", label: "D♭♭♭", alias: "", cents: 26.67 },
    { key: "cs", label: "C♯", alias: "", cents: 53.33 },
    { key: "dbb", label: "D♭♭", alias: "", cents: 80 },
    { key: "css", label: "C♯♯", alias: "", cents: 106.67 },
    { key: "db", label: "D♭", alias: "", cents: 133.33 },
    { key: "csss", label: "C♯♯♯", alias: "", cents: 160 },
    { key: "d", label: "D", alias: "", cents: 186.67 },
    { key: "ebbb", label: "E♭♭♭", alias: "", cents: 213.33 },
    { key: "ds", label: "D♯", alias: "", cents: 240 },
    { key: "ebb", label: "E♭♭", alias: "", cents: 266.67 },
    { key: "dss", label: "D♯♯", alias: "", cents: 293.33 },
    { key: "eb", label: "E♭", alias: "", cents: 320 },
    { key: "fbbb", label: "F♭♭♭", alias: "", cents: 346.67 },
    { key: "e", label: "E", alias: "", cents: 373.33 },
    { key: "fbb", label: "F♭♭", alias: "", cents: 400 },
    { key: "es", label: "E♯", alias: "", cents: 426.67 },
    { key: "fb", label: "F♭", alias: "", cents: 453.33 },
    { key: "ess", label: "E♯♯", alias: "", cents: 480 },
    { key: "f", label: "F", alias: "", cents: 506.67 },
    { key: "gbbb", label: "G♭♭♭", alias: "", cents: 533.33 },
    { key: "fs", label: "F♯", alias: "", cents: 560 },
    { key: "gbb", label: "G♭♭", alias: "", cents: 586.67 },
    { key: "fss", label: "F♯♯", alias: "", cents: 613.33 },
    { key: "gb", label: "G♭", alias: "", cents: 640 },
    { key: "fsss", label: "F♯♯♯", alias: "", cents: 666.67 },
    { key: "g", label: "G", alias: "", cents: 693.33 },
    { key: "abbb", label: "A♭♭♭", alias: "", cents: 720 },
    { key: "gs", label: "G♯", alias: "", cents: 746.67 },
    { key: "abb", label: "A♭♭", alias: "", cents: 773.33 },
    { key: "gss", label: "G♯♯", alias: "", cents: 800 },
    { key: "ab", label: "A♭", alias: "", cents: 826.67 },
    { key: "gsss", label: "G♯♯♯", alias: "", cents: 853.33 },
    { key: "a", label: "A", alias: "", cents: 880 },
    { key: "bbbb", label: "B♭♭♭", alias: "", cents: 906.67 },
    { key: "as", label: "A♯", alias: "", cents: 933.33 },
    { key: "bbb", label: "B♭♭", alias: "", cents: 960 },
    { key: "ass", label: "A♯♯", alias: "", cents: 986.67 },
    { key: "bb", label: "B♭", alias: "", cents: 1013.33 },
    { key: "cbbb", label: "C♭♭♭", alias: "", cents: 1040 },
    { key: "b", label: "B", alias: "", cents: 1066.67 },
    { key: "cbb", label: "C♭♭", alias: "", cents: 1093.33 },
    { key: "bs", label: "B♯", alias: "", cents: 1120 },
    { key: "cb", label: "C♭", alias: "", cents: 1146.67 },
    { key: "bss", label: "B♯♯", alias: "", cents: 1173.33 },
  ],

  "53tet": [
    { key: "c", label: "C", alias: "", cents: 0 },
    { key: "bs", label: "B♯", alias: "", cents: 22.64 },
    { key: "asss", label: "A♯♯♯", alias: "", cents: 45.28 },
    { key: "ebbb", label: "E♭♭♭", alias: "", cents: 67.92 },
    { key: "db", label: "D♭", alias: "", cents: 90.57 },
    { key: "cs", label: "C♯", alias: "", cents: 113.21 },
    { key: "bss", label: "B♯♯", alias: "", cents: 135.85 },
    { key: "fbbb", label: "F♭♭♭", alias: "", cents: 158.49 },
    { key: "ebb", label: "E♭♭", alias: "", cents: 181.13 },
    { key: "d", label: "D", alias: "", cents: 203.77 },
    { key: "css", label: "C♯♯", alias: "", cents: 226.42 },
    { key: "bsss", label: "B♯♯♯", alias: "", cents: 249.06 },
    { key: "fbb", label: "F♭♭", alias: "", cents: 271.7 },
    { key: "eb", label: "E♭", alias: "", cents: 294.34 },
    { key: "ds", label: "D♯", alias: "", cents: 316.98 },
    { key: "csss", label: "C♯♯♯", alias: "", cents: 339.62 },
    { key: "gbbb", label: "G♭♭♭", alias: "", cents: 362.26 },
    { key: "fb", label: "F♭", alias: "", cents: 384.91 },
    { key: "e", label: "E", alias: "", cents: 407.55 },
    { key: "dss", label: "D♯♯", alias: "", cents: 430.19 },
    { key: "abbbb", label: "A♭♭♭♭", alias: "", cents: 452.83 },
    { key: "gbb", label: "G♭♭", alias: "", cents: 475.47 },
    { key: "f", label: "F", alias: "", cents: 498.11 },
    { key: "es", label: "E♯", alias: "", cents: 520.75 },
    { key: "dsss", label: "D♯♯♯", alias: "", cents: 543.4 },
    { key: "abbb", label: "A♭♭♭", alias: "", cents: 566.04 },
    { key: "gb", label: "G♭", alias: "", cents: 588.68 },
    { key: "fs", label: "F♯", alias: "", cents: 611.32 },
    { key: "ess", label: "E♯♯", alias: "", cents: 633.96 },
    { key: "bbbbb", label: "B♭♭♭♭", alias: "", cents: 656.6 },
    { key: "abb", label: "A♭♭", alias: "", cents: 679.25 },
    { key: "g", label: "G", alias: "", cents: 701.89 },
    { key: "fss", label: "F♯♯", alias: "", cents: 724.53 },
    { key: "esss", label: "E♯♯♯", alias: "", cents: 747.17 },
    { key: "bbbb", label: "B♭♭♭", alias: "", cents: 769.81 },
    { key: "ab", label: "A♭", alias: "", cents: 792.45 },
    { key: "gs", label: "G♯", alias: "", cents: 815.09 },
    { key: "fsss", label: "F♯♯♯", alias: "", cents: 837.74 },
    { key: "cbbb", label: "C♭♭♭", alias: "", cents: 860.38 },
    { key: "bbb", label: "B♭♭", alias: "", cents: 883.02 },
    { key: "a", label: "A", alias: "", cents: 905.66 },
    { key: "gss", label: "G♯♯", alias: "", cents: 928.3 },
    { key: "dbbbb", label: "D♭♭♭♭", alias: "", cents: 950.94 },
    { key: "cbb", label: "C♭♭", alias: "", cents: 973.58 },
    { key: "bb", label: "B♭", alias: "", cents: 996.23 },
    { key: "as", label: "A♯", alias: "", cents: 1018.87 },
    { key: "gsss", label: "G♯♯♯", alias: "", cents: 1041.51 },
    { key: "dbbb", label: "D♭♭♭", alias: "", cents: 1064.15 },
    { key: "cb", label: "C♭", alias: "", cents: 1086.79 },
    { key: "b", label: "B", alias: "", cents: 1109.43 },
    { key: "ass", label: "A♯♯", alias: "", cents: 1132.08 },
    { key: "ebbbb", label: "E♭♭♭♭", alias: "", cents: 1154.72 },
    { key: "dbb", label: "D♭♭", alias: "", cents: 1177.36 },
  ],

  "55tet": [
    { key: "c", label: "C", alias: "", cents: 0 },
    { key: "dbb", label: "D♭♭", alias: "", cents: 21.82 },
    { key: "ebbbb", label: "E♭♭♭♭", alias: "", cents: 43.64 },
    { key: "bss", label: "B♯♯", alias: "", cents: 65.45 },
    { key: "cs", label: "C♯", alias: "", cents: 87.27 },
    { key: "db", label: "D♭", alias: "", cents: 109.09 },
    { key: "ebbb", label: "E♭♭♭", alias: "", cents: 130.91 },
    { key: "bsss", label: "B♯♯♯", alias: "", cents: 152.73 },
    { key: "css", label: "C♯♯", alias: "", cents: 174.55 },
    { key: "d", label: "D", alias: "", cents: 196.36 },
    { key: "ebb", label: "E♭♭", alias: "", cents: 218.18 },
    { key: "fbbb", label: "F♭♭♭", alias: "", cents: 240 },
    { key: "csss", label: "C♯♯♯", alias: "", cents: 261.82 },
    { key: "ds", label: "D♯", alias: "", cents: 283.64 },
    { key: "eb", label: "E♭", alias: "", cents: 305.45 },
    { key: "fbb", label: "F♭♭", alias: "", cents: 327.27 },
    { key: "gbbbb", label: "G♭♭♭♭", alias: "", cents: 349.09 },
    { key: "dss", label: "D♯♯", alias: "", cents: 370.91 },
    { key: "e", label: "E", alias: "", cents: 392.73 },
    { key: "fb", label: "F♭", alias: "", cents: 414.55 },
    { key: "gbbb", label: "G♭♭♭", alias: "", cents: 436.36 },
    { key: "dsss", label: "D♯♯♯", alias: "", cents: 458.18 },
    { key: "es", label: "E♯", alias: "", cents: 480 },
    { key: "f", label: "F", alias: "", cents: 501.82 },
    { key: "gbb", label: "G♭♭", alias: "", cents: 523.64 },
    { key: "abbbb", label: "A♭♭♭♭", alias: "", cents: 545.45 },
    { key: "ess", label: "E♯♯", alias: "", cents: 567.27 },
    { key: "fs", label: "F♯", alias: "", cents: 589.09 },
    { key: "gb", label: "G♭", alias: "", cents: 610.91 },
    { key: "abbb", label: "A♭♭♭", alias: "", cents: 632.73 },
    { key: "esss", label: "E♯♯♯", alias: "", cents: 654.55 },
    { key: "fss", label: "F♯♯", alias: "", cents: 676.36 },
    { key: "g", label: "G", alias: "", cents: 698.18 },
    { key: "abb", label: "A♭♭", alias: "", cents: 720 },
    { key: "bbbbb", label: "B♭♭♭♭", alias: "", cents: 741.82 },
    { key: "fsss", label: "F♯♯♯", alias: "", cents: 763.64 },
    { key: "gs", label: "G♯", alias: "", cents: 785.45 },
    { key: "ab", label: "A♭", alias: "", cents: 807.27 },
    { key: "bbbb", label: "B♭♭♭", alias: "", cents: 829.09 },
    { key: "fssss", label: "F♯♯♯♯", alias: "", cents: 850.91 },
    { key: "gss", label: "G♯♯", alias: "", cents: 872.73 },
    { key: "a", label: "A", alias: "", cents: 894.55 },
    { key: "bbb", label: "B♭♭", alias: "", cents: 916.36 },
    { key: "cbbb", label: "C♭♭♭", alias: "", cents: 938.18 },
    { key: "gsss", label: "G♯♯♯", alias: "", cents: 960 },
    { key: "as", label: "A♯", alias: "", cents: 981.82 },
    { key: "bb", label: "B♭", alias: "", cents: 1003.64 },
    { key: "cbb", label: "C♭♭", alias: "", cents: 1025.45 },
    { key: "dbbbb", label: "D♭♭♭♭", alias: "", cents: 1047.27 },
    { key: "ass", label: "A♯♯", alias: "", cents: 1069.09 },
    { key: "b", label: "B", alias: "", cents: 1090.91 },
    { key: "cb", label: "C♭", alias: "", cents: 1112.73 },
    { key: "dbbb", label: "D♭♭♭", alias: "", cents: 1134.55 },
    { key: "asss", label: "A♯♯♯", alias: "", cents: 1156.36 },
    { key: "bs", label: "B♯", alias: "", cents: 1178.18 },
  ],

  "quarter": [
    { key: "c",  label: "C",  alias: "B♯",cents: 0 },
    { key: "c+", label: "C+", alias: "",  cents: 50 },
    { key: "cs", label: "C♯", alias: "D♭",cents: 100 },
    { key: "d-", label: "D-", alias: "",  cents: 150 },
    { key: "d",  label: "D",  alias: "",  cents: 200 },
    { key: "d+", label: "D+", alias: "",  cents: 250 },
    { key: "ds", label: "D♯", alias: "E♭",cents: 300 },
    { key: "e-", label: "E-", alias: "",  cents: 350 },
    { key: "e",  label: "E",  alias: "F♭",cents: 400 },
    { key: "e+", label: "E+", alias: "",  cents: 450 },
    { key: "f",  label: "F",  alias: "E♯",cents: 500 },
    { key: "f+", label: "F+", alias: "",  cents: 550 },
    { key: "fs", label: "F♯", alias: "G♭",cents: 600 },
    { key: "g-", label: "G-", alias: "",  cents: 650 },
    { key: "g",  label: "G",  alias: "",  cents: 700 },
    { key: "g+", label: "G+", alias: "",  cents: 750 },
    { key: "gs", label: "G♯", alias: "A♭",cents: 800 },
    { key: "a-", label: "A-", alias: "",  cents: 850 },
    { key: "a",  label: "A",  alias: "",  cents: 900 },
    { key: "a+", label: "A+", alias: "",  cents: 950 },
    { key: "as", label: "A♯", alias: "B♭",cents: 1000 },
    { key: "b-", label: "B-", alias: "",  cents: 1050 },
    { key: "b",  label: "B",  alias: "C♭",cents: 1100 },
    { key: "b+", label: "B+", alias: "",  cents: 1150 },
  ],

  "meantone": [
    { key: "c",  label: "C",  alias: "",	cents: 0 },
    { key: "cs", label: "C♯",	alias: "",	cents: 76.05 },
    { key: "db", label: "D♭",	alias: "",	cents: 117.11 },
    { key: "d",  label: "D",  alias: "",	cents: 193.16 },
    { key: "ds", label: "D♯",	alias: "",	cents: 269.21 },
    { key: "eb", label: "E♭",	alias: "",	cents: 310.26 },
    { key: "e",  label: "E",  alias: "",	cents: 386.31 },
    { key: "es", label: "E♯",	alias: "",	cents: 462.36 },
    { key: "f",  label: "F",  alias: "",	cents: 503.42 },
    { key: "fs", label: "F♯",	alias: "",	cents: 579.47 },
    { key: "gb", label: "G♭",	alias: "",	cents: 620.53 },
    { key: "g",  label: "G",	alias: "",	cents: 696.58 },
    { key: "gs", label: "G♯",	alias: "",	cents: 772.63 },
    { key: "ab", label: "A♭",	alias: "",	cents: 813.69 },
    { key: "a",  label: "A",  alias: "",	cents: 889.74 },
    { key: "as", label: "A♯",	alias: "",	cents: 965.79 },
    { key: "bb", label: "B♭",	alias: "",	cents: 1006.84 },
    { key: "b",  label: "B",  alias: "",	cents: 1082.89 },
    { key: "bs", label: "B♯",	alias: "",	cents: 1158.94 },
  ],

  "pythagorean": [
    { key: "c",  label: "C",  alias: "",	cents: 0 },
    { key: "db", label: "D♭",	alias: "",	cents: 90 },
    { key: "cs", label: "C♯",	alias: "",	cents: 114 },
    { key: "d",  label: "D",  alias: "",	cents: 204 },
    { key: "eb", label: "E♭",	alias: "",	cents: 294 },
    { key: "ds", label: "D♯",	alias: "",	cents: 318 },
    { key: "e",  label: "E",  alias: "",	cents: 408 },
    { key: "f",  label: "F",  alias: "",	cents: 498 },
    { key: "gb", label: "G♭",	alias: "",	cents: 588 },
    { key: "fs", label: "F♯",	alias: "",	cents: 612 },
    { key: "g",  label: "G",	alias: "",	cents: 702 },
    { key: "ab", label: "A♭",	alias: "",	cents: 792 },
    { key: "gs", label: "G♯",	alias: "",	cents: 816 },
    { key: "a",  label: "A",  alias: "",	cents: 906 },
    { key: "bb", label: "B♭",	alias: "",	cents: 996 },
    { key: "as", label: "A♯",	alias: "",	cents: 1020 },
    { key: "b",  label: "B",  alias: "",	cents: 1110 },
  ],

  "indian": [
    { key: "c",   label: "C",   alias: "", cents: 0 },
    { key: "db1", label: "D♭",  alias: "", cents: 90 },
    { key: "db2", label: "D♭'",	alias: "", cents: 112 },
    { key: "d1",  label: "D",   alias: "", cents: 182 },
    { key: "d2",  label: "D'",  alias: "", cents: 204 },
    { key: "eb1", label: "E♭",	alias: "", cents: 294 },
    { key: "eb2", label: "E♭'",	alias: "", cents: 316 },
    { key: "e1",  label: "E",	  alias: "", cents: 386 },
    { key: "e2",  label: "E'",	alias: "", cents: 408 },
    { key: "f1",  label: "F",   alias: "", cents: 498 },
    { key: "f2",  label: "F'",  alias: "", cents: 520 },
    { key: "fs1", label: "F♯",  alias: "", cents: 590 },
    { key: "fs2", label: "F♯'", alias: "", cents: 610 },
    { key: "g",   label: "G",	  alias: "", cents: 702 },
    { key: "ab1", label: "A♭",	alias: "", cents: 792 },
    { key: "ab2", label: "A♭'",	alias: "", cents: 814 },
    { key: "a1",  label: "A",   alias: "", cents: 884 },
    { key: "a2",  label: "A'",  alias: "", cents: 906 },
    { key: "bb1", label: "B♭",	alias: "", cents: 996 },
    { key: "bb2", label: "B♭'",	alias: "", cents: 1018 },
    { key: "b1",  label: "B",   alias: "", cents: 1088 },
    { key: "b2",  label: "B'",  alias: "", cents: 1110 },
  ],

  "arab": [
    { key: "c",   label: "C",   alias: "", cents: 0 },
    { key: "db",  label: "D♭",  alias: "", cents: 90.22 },
    { key: "d1",  label: "D",   alias: "", cents: 180.45 },
    { key: "d2",  label: "D'",  alias: "", cents: 203.91 },
    { key: "eb",  label: "E♭",	alias: "", cents: 294.13 },
    { key: "e1",  label: "E",	  alias: "", cents: 384.36 },
    { key: "e2",  label: "E'",	alias: "", cents: 407.82 },
    { key: "f",   label: "F",   alias: "", cents: 498.04 },
    { key: "fs1", label: "F♯",  alias: "", cents: 588.27 },
    { key: "fs2", label: "F♯'", alias: "", cents: 678.49 },
    { key: "g",   label: "G",	  alias: "", cents: 701.96 },
    { key: "ab",  label: "A♭",	alias: "", cents: 792.18 },
    { key: "a1",  label: "A",   alias: "", cents: 882.4 },
    { key: "a2",  label: "A'",  alias: "", cents: 905.87 },
    { key: "bb",  label: "B♭",	alias: "", cents: 996.09 },
    { key: "b1",  label: "B",   alias: "", cents: 1086.31 },
    { key: "b2",  label: "B'",  alias: "", cents: 1176.54 },
  ],

  "persian": [
    { key: "c",   label: "C",   alias: "", cents: 0 },
    { key: "db",  label: "D♭",  alias: "", cents: 133.24 },
    { key: "d",   label: "D",   alias: "", cents: 203.91 },
    { key: "eb1", label: "E♭",	alias: "", cents: 294.13 },
    { key: "eb2", label: "E♭'",	alias: "", cents: 337.15 },
    { key: "e",   label: "E", 	alias: "", cents: 407.82 },
    { key: "f",   label: "F",   alias: "", cents: 498.04 },
    { key: "fs1", label: "F♯",  alias: "", cents: 568.72 },
    { key: "fs2", label: "F♯'", alias: "", cents: 631.28 },
    { key: "g",   label: "G",   alias: "", cents: 701.96 },
    { key: "ab1", label: "A♭",	alias: "", cents: 792.18 },
    { key: "ab2", label: "A♭'",	alias: "", cents: 835.19 },
    { key: "a",   label: "A",   alias: "", cents: 905.87 },
    { key: "bb1", label: "B♭",	alias: "", cents: 996.09 },
    { key: "bb2", label: "B♭'",	alias: "", cents: 1039.1 },
    { key: "b",   label: "B",   alias: "", cents: 1109.78 },
  ],
};